# Arquitecturas híbridas

## Librerías

In [1]:
import pandas as pd
import numpy as np
import os
import torch
import torch.nn as nn
from torchvision import models, transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score, 
                             f1_score, cohen_kappa_score, confusion_matrix, classification_report)
from tqdm import tqdm

## Fusión temprana

In [2]:
# --- CONFIGURACIÓN ---
# Detectamos si tienes GPU para que la extracción de características vuele
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🚀 Usando dispositivo: {device}")

# Rutas
csv_path = 'Datos/metadata.csv'
images_dir = 'Datos/images'

# ==========================================
# 1. PREPARACIÓN DE LA CNN (ResNet101)
# ==========================================
print("\n🧠 Cargando ResNet101 preentrenada...")

# Función para obtener el modelo extractor de características
def get_feature_extractor():
    # Cargamos ResNet101 con pesos de ImageNet
    model = models.resnet101(weights=models.ResNet101_Weights.DEFAULT)
    
    # TRUCO: Quitamos la última capa (fc) que es la que clasifica (perro, gato...)
    # La sustituimos por una identidad para que pase el vector directo
    # ResNet101 saca un vector de 2048 características antes de la clasificación
    model.fc = nn.Identity()
    
    model.to(device)
    model.eval() # Modo evaluación (congela dropout, etc)
    return model

cnn_extractor = get_feature_extractor()

# Transformaciones necesarias para que ResNet entienda las fotos
preprocess = transforms.Compose([
    # ALERTA: Pasamos una TUPLA (224, 224).
    # Esto aplasta o estira la imagen para que encaje exacta, sin recortar bordes.
    transforms.Resize((224, 224)), 
    
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# ==========================================
# 2. CARGA DE DATOS E IMÁGENES
# ==========================================
class SkinLesionDataset(Dataset):
    def __init__(self, df, root_dir, transform=None):
        self.df = df
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        # Reconstruimos la ruta: dataset_final/images/CLASE/FOTO.png
        img_name = row['img_id']
        label_name = row['diagnostic']
        img_path = os.path.join(self.root_dir, label_name, img_name)
        
        try:
            image = Image.open(img_path).convert('RGB')
        except:
            # Si falla una imagen, creamos una negra (no debería pasar si limpiamos bien)
            image = Image.new('RGB', (224, 224))
            
        if self.transform:
            image = self.transform(image)
            
        return image

# Leemos el CSV
df = pd.read_csv(csv_path)
print(f"📂 Dataset cargado: {len(df)} muestras")

# Dataset y DataLoader para ir por lotes
dataset = SkinLesionDataset(df, images_dir, transform=preprocess)
dataloader = DataLoader(dataset, batch_size=32, shuffle=False) # Shuffle False para mantener orden con CSV!


🚀 Usando dispositivo: cpu

🧠 Cargando ResNet101 preentrenada...
📂 Dataset cargado: 802 muestras


In [3]:

# ==========================================
# 3. EXTRACCIÓN DE VECTORES (EMBEDDINGS)
# ==========================================
print("\n📸 Extrayendo características visuales (Esto puede tardar un poco)...")

features_list = []

with torch.no_grad(): # No necesitamos gradientes, solo inferencia
    for images in tqdm(dataloader):
        images = images.to(device)
        # Pasamos las fotos por la ResNet
        outputs = cnn_extractor(images)
        # Pasamos a CPU y numpy
        features_list.append(outputs.cpu().numpy())

# Unimos todos los bloques en una gran matriz de características
# Tamaño esperado: (N_muestras, 2048)
image_features = np.concatenate(features_list, axis=0)
print(f"✅ Extracción completada. Dimensión de features visuales: {image_features.shape}")

# Convertimos a DataFrame para unirlo bonito
feat_cols = [f'img_feat_{i}' for i in range(image_features.shape[1])]
df_features = pd.DataFrame(image_features, columns=feat_cols)



📸 Extrayendo características visuales (Esto puede tardar un poco)...


100%|██████████| 26/26 [01:47<00:00,  4.14s/it]

✅ Extracción completada. Dimensión de features visuales: (802, 2048)


In [4]:

# ==========================================
# 4. PREPARACIÓN DATOS TABULARES (Limpieza)
# ==========================================
print("\n⚙️ Procesando datos tabulares...")

# Hacemos copia para no tocar el original
df_tab = df.copy()

# Variables a ignorar
ignore_cols = ['patient_id', 'lesion_id', 'img_id', 'diagnostic', 'biopsed', 'path'] # path si existiera
cols_to_use = [c for c in df_tab.columns if c not in ignore_cols]

X_tab = df_tab[cols_to_use]
y = df_tab['diagnostic']

# Limpieza (Rellenar nulos y One-Hot Encoding)
# 1. Rellenar
for col in X_tab.columns:
    if X_tab[col].dtype == 'object':
        X_tab[col] = X_tab[col].fillna('DESCONOCIDO')
    else:
        X_tab[col] = X_tab[col].fillna(X_tab[col].mean())

# 2. Convertir texto a números (One-Hot)
X_tab = pd.get_dummies(X_tab, drop_first=True)

print(f"   - Features Tabulares: {X_tab.shape[1]} columnas")

# ==========================================
# 5. FUSIÓN (CONCATENACIÓN)
# ==========================================
print("\n🔗 FUSIONANDO (Early Fusion)...")

# Reseteamos índices para evitar problemas al concatenar
X_tab.reset_index(drop=True, inplace=True)
df_features.reset_index(drop=True, inplace=True)

# Unimos horizontalmente: [Datos Tabulares | Vector ResNet]
X_final = pd.concat([X_tab, df_features], axis=1)

print(f"✨ Dataset Híbrido Final: {X_final.shape[0]} filas x {X_final.shape[1]} columnas")
# Codificamos la etiqueta (Target) a números (0, 1, 2...)
le = LabelEncoder()
y_encoded = le.fit_transform(y)



⚙️ Procesando datos tabulares...
   - Features Tabulares: 66 columnas

🔗 FUSIONANDO (Early Fusion)...
✨ Dataset Híbrido Final: 802 filas x 2114 columnas


C:\Users\pedro\AppData\Local\Temp\ipykernel_30532\1936509309.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_tab[col] = X_tab[col].fillna('DESCONOCIDO')
C:\Users\pedro\AppData\Local\Temp\ipykernel_30532\1936509309.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_tab[col] = X_tab[col].fillna(X_tab[col].mean())


In [6]:

# ==========================================
# 6. ENTRENAMIENTO Y EVALUACIÓN
# ==========================================
print("\n🏋️ Entrenando Gradient Boosting (Esto es potente)...")

X_train, X_test, y_train, y_test = train_test_split(X_final, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

# Usamos GradientBoostingClassifier de Sklearn (robusto y potente)
# Si quisieras XGBoost específico: import xgboost as xgb; clf = xgb.XGBClassifier(...)
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
#clf = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42, use_label_encoder=False, eval_metric='mlogloss')
#clf = RandomForestClassifier(n_estimators=400, random_state=42)
clf.fit(X_train, y_train)

# Predicción
y_pred = clf.predict(X_test)

# ==========================================
# 7. MÉTRICAS SOLICITADAS
# ==========================================
print("\n📊 --- RESULTADOS DE LA EVALUACIÓN ---")

# Calculamos métricas
acc = accuracy_score(y_test, y_pred)
# 'weighted' calcula la media ponderada por el número de muestras de cada clase (ideal para multiclass)
prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
rec = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
kappa = cohen_kappa_score(y_test, y_pred)
conf_mat = confusion_matrix(y_test, y_pred)

print(f"✅ Accuracy (Exactitud):  {acc:.4f}")
print(f"✅ Precision (Precisión): {prec:.4f}")
print(f"✅ Recall (Sensibilidad): {rec:.4f}")
print(f"✅ F1-Score:              {f1:.4f}")
print(f"✅ Kappa de Cohen:        {kappa:.4f}")

print("\n🔍 Matriz de Confusión:")
print(conf_mat)

print("\n📋 Reporte Detallado:")
# Recuperamos los nombres reales de las clases para el reporte
target_names = le.inverse_transform(sorted(list(set(y_test))))
print(classification_report(y_test, y_pred, target_names=target_names))


🏋️ Entrenando Gradient Boosting (Esto es potente)...

📊 --- RESULTADOS DE LA EVALUACIÓN ---
✅ Accuracy (Exactitud):  0.6025
✅ Precision (Precisión): 0.6063
✅ Recall (Sensibilidad): 0.6025
✅ F1-Score:              0.5962
✅ Kappa de Cohen:        0.5132

🔍 Matriz de Confusión:
[[21  5  0  1  3  0]
 [ 6 18  0  1  4  1]
 [ 1  0  2  2  4  2]
 [ 1  2  0 21  2  4]
 [ 3  8  1  0 18  0]
 [ 2  4  1  6  0 17]]

📋 Reporte Detallado:
              precision    recall  f1-score   support

         ACK       0.62      0.70      0.66        30
         BCC       0.49      0.60      0.54        30
         MEL       0.50      0.18      0.27        11
         NEV       0.68      0.70      0.69        30
         SCC       0.58      0.60      0.59        30
         SEK       0.71      0.57      0.63        30

    accuracy                           0.60       161
   macro avg       0.60      0.56      0.56       161
weighted avg       0.61      0.60      0.60       161



## Fusión tardía (Stacking)

In [7]:
import pandas as pd
import numpy as np
import os
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score, 
                             f1_score, cohen_kappa_score, confusion_matrix, classification_report)
from tqdm import tqdm


In [8]:

# --- CONFIGURACIÓN ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🚀 Usando dispositivo: {device}")

csv_path = 'Datos/metadata.csv'
images_dir = 'Datos/images'

# ==========================================
# 1. PREPARACIÓN DE DATOS (SPLIT 3 VÍAS)
# ==========================================
print("\n✂️ Dividiendo datos en Train (Modelos Base), Val (Meta-Modelo) y Test (Final)...")
df = pd.read_csv(csv_path)

# Codificamos las etiquetas a números (0, 1, 2...)
le = LabelEncoder()
df['label_encoded'] = le.fit_transform(df['diagnostic'])
num_classes = len(le.classes_)
print(f"Clases detectadas: {le.classes_}")

# Split 1: Separamos Test (20%)
X_temp, X_test, y_temp, y_test = train_test_split(
    df, df['label_encoded'], test_size=0.2, random_state=42, stratify=df['label_encoded']
)

# Split 2: Del resto, separamos Validación (20% del total original aprox)
# Train será el 60% del total, Val el 20%, Test el 20%
X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp, test_size=0.25, random_state=42, stratify=y_temp
)

print(f"   - Train set: {len(X_train)} (Para entrenar ResNet, XGB, RF)")
print(f"   - Val set:   {len(X_val)}   (Para entrenar al MLP Stacker)")
print(f"   - Test set:  {len(X_test)}  (Para evaluación final)")


🚀 Usando dispositivo: cpu

✂️ Dividiendo datos en Train (Modelos Base), Val (Meta-Modelo) y Test (Final)...
Clases detectadas: ['ACK' 'BCC' 'MEL' 'NEV' 'SCC' 'SEK']
   - Train set: 480 (Para entrenar ResNet, XGB, RF)
   - Val set:   161   (Para entrenar al MLP Stacker)
   - Test set:  161  (Para evaluación final)


In [9]:

# ==========================================
# 2. MODELO DE IMAGEN (RESNET101 - FINE TUNING)
# ==========================================
print("\n🧠 Configurando ResNet101 para Fine-Tuning...")

# Dataset Personalizado
class SkinDataset(Dataset):
    def __init__(self, dataframe, root_dir, transform=None):
        self.df = dataframe.reset_index(drop=True)
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = os.path.join(self.root_dir, row['diagnostic'], row['img_id'])
        label = row['label_encoded']
        try:
            image = Image.open(img_path).convert('RGB')
        except:
            image = Image.new('RGB', (224, 224)) # Fallback
        
        if self.transform:
            image = self.transform(image)
        return image, label

# Transformaciones
train_transforms = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomHorizontalFlip(), transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
val_test_transforms = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# DataLoaders
train_loader = DataLoader(SkinDataset(X_train, images_dir, train_transforms), batch_size=32, shuffle=True)
val_loader = DataLoader(SkinDataset(X_val, images_dir, val_test_transforms), batch_size=32, shuffle=False)
test_loader = DataLoader(SkinDataset(X_test, images_dir, val_test_transforms), batch_size=32, shuffle=False)

# Definir Modelo
resnet = models.resnet101(weights=models.ResNet101_Weights.DEFAULT)
# Congelamos capas base (opcional, para ir más rápido)
for param in resnet.parameters():
    param.requires_grad = False
# Cambiamos la capa final para clasificar nuestras clases
resnet.fc = nn.Linear(resnet.fc.in_features, num_classes)
resnet = resnet.to(device)

# Entrenamiento Rápido de ResNet
optimizer = optim.Adam(resnet.fc.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

print("🏋️ Entrenando ResNet (Fine-Tuning de la última capa)...")
resnet.train()
epochs = 5 # Pocas épocas para demostración
for epoch in range(epochs):
    running_loss = 0.0
    for inputs, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}"):
        inputs, labels = inputs.to(device), labels.to(device, dtype=torch.long)
        optimizer.zero_grad()
        outputs = resnet(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

# Función para obtener PROBABILIDADES
def get_probs(model, loader):
    model.eval()
    probs_list = []
    with torch.no_grad():
        for inputs, _ in loader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            # Aplicamos Softmax para tener probabilidades (0 a 1)
            probs = torch.nn.functional.softmax(outputs, dim=1)
            probs_list.append(probs.cpu().numpy())
    return np.concatenate(probs_list)

print("📸 Generando predicciones de ResNet para Val y Test...")
resnet_probs_val = get_probs(resnet, val_loader)
resnet_probs_test = get_probs(resnet, test_loader)



🧠 Configurando ResNet101 para Fine-Tuning...
🏋️ Entrenando ResNet (Fine-Tuning de la última capa)...


Epoch 5/5: 100%|██████████| 15/15 [01:47<00:00,  7.18s/it]


📸 Generando predicciones de ResNet para Val y Test...


In [10]:

# ==========================================
# 3. MODELOS TABULARES (XGBOOST y RANDOM FOREST)
# ==========================================
print("\n📊 Entrenando Modelos Tabulares...")

# Preprocesamiento Tabular
def process_tabular(df_subset):
    df_proc = df_subset.drop(columns=['patient_id', 'lesion_id', 'img_id', 'diagnostic', 'path', 'label_encoded', 'biopsed'], errors='ignore')
    # Rellenar y One-Hot
    for col in df_proc.columns:
        if df_proc[col].dtype == 'object':
            df_proc[col] = df_proc[col].fillna('DESCONOCIDO')
        else:
            df_proc[col] = df_proc[col].fillna(df_proc[col].mean())
    return pd.get_dummies(df_proc, drop_first=True)

# Procesamos todos juntos para alinear columnas, luego separamos
df_all_tab = pd.concat([X_train, X_val, X_test])
df_all_proc = process_tabular(df_all_tab)

# Recuperamos los splits procesados
tab_train = df_all_proc.iloc[:len(X_train)]
tab_val = df_all_proc.iloc[len(X_train):len(X_train)+len(X_val)]
tab_test = df_all_proc.iloc[len(X_train)+len(X_val):]

# 3.1 Random Forest
rf = RandomForestClassifier(n_estimators=400, random_state=42)
rf.fit(tab_train, y_train)
rf_probs_val = rf.predict_proba(tab_val)
rf_probs_test = rf.predict_proba(tab_test)

# 3.2 XGBoost
xgb = XGBClassifier(n_estimators=400, random_state=42, eval_metric='mlogloss', use_label_encoder=False)
xgb.fit(tab_train, y_train)
xgb_probs_val = xgb.predict_proba(tab_val)
xgb_probs_test = xgb.predict_proba(tab_test)

print("✅ Modelos tabulares entrenados y predicciones generadas.")



📊 Entrenando Modelos Tabulares...


c:\Users\pedro\anaconda4\Lib\site-packages\xgboost\training.py:199: UserWarning: [15:03:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


✅ Modelos tabulares entrenados y predicciones generadas.


In [11]:

# ==========================================
# 4. STACKING (FUSIÓN TARDÍA CON MLP)
# ==========================================
print("\n🔗 Construyendo el Meta-Modelo (Stacking con MLP)...")

# Construimos la entrada para el meta-modelo concatenando las probabilidades
# Input = [Probs ResNet (6 cols) | Probs RF (6 cols) | Probs XGB (6 cols)]
X_stack_val = np.hstack([resnet_probs_val, rf_probs_val, xgb_probs_val])
X_stack_test = np.hstack([resnet_probs_test, rf_probs_test, xgb_probs_test])

print(f"   - Dimensiones entrada Stacking: {X_stack_val.shape}")

# Usamos un MLPClassifier (Perceptrón Multicapa) como meta-aprendiz
# Es el "Juez" que decide a quién creer
meta_model = MLPClassifier(hidden_layer_sizes=(128, 64, 32), activation='relu', solver='adam', max_iter=2000, random_state=42)
meta_model.fit(X_stack_val, y_val)

print("🔮 Prediciendo resultado final con el Stacking...")
y_final_pred = meta_model.predict(X_stack_test)



🔗 Construyendo el Meta-Modelo (Stacking con MLP)...
   - Dimensiones entrada Stacking: (161, 18)
🔮 Prediciendo resultado final con el Stacking...


In [12]:

# ==========================================
# 5. EVALUACIÓN FINAL
# ==========================================
print("\n🏆 --- RESULTADOS FINALES (STACKING) ---")

# Calculamos métricas
acc = accuracy_score(y_test, y_final_pred)
prec = precision_score(y_test, y_final_pred, average='weighted', zero_division=0)
rec = recall_score(y_test, y_final_pred, average='weighted')
f1 = f1_score(y_test, y_final_pred, average='weighted')
kappa = cohen_kappa_score(y_test, y_final_pred)
conf_mat = confusion_matrix(y_test, y_final_pred)

print(f"✅ Accuracy:        {acc:.4f}")
print(f"✅ Precision:       {prec:.4f}")
print(f"✅ Recall:          {rec:.4f}")
print(f"✅ F1-Score:        {f1:.4f}")
print(f"✅ Kappa de Cohen:  {kappa:.4f}")

print("\n🔍 Matriz de Confusión:")
print(conf_mat)

print("\n📋 Reporte por Clase:")
print(classification_report(y_test, y_final_pred, target_names=le.classes_))


🏆 --- RESULTADOS FINALES (STACKING) ---
✅ Accuracy:        0.6273
✅ Precision:       0.6322
✅ Recall:          0.6273
✅ F1-Score:        0.6223
✅ Kappa de Cohen:  0.5440

🔍 Matriz de Confusión:
[[23  3  0  1  1  2]
 [ 4 15  0  0  9  2]
 [ 1  2  4  2  0  2]
 [ 3  1  0 22  0  4]
 [ 5  9  0  0 15  1]
 [ 0  1  1  5  1 22]]

📋 Reporte por Clase:
              precision    recall  f1-score   support

         ACK       0.64      0.77      0.70        30
         BCC       0.48      0.50      0.49        30
         MEL       0.80      0.36      0.50        11
         NEV       0.73      0.73      0.73        30
         SCC       0.58      0.50      0.54        30
         SEK       0.67      0.73      0.70        30

    accuracy                           0.63       161
   macro avg       0.65      0.60      0.61       161
weighted avg       0.63      0.63      0.62       161



## Red Neuronal Mixta

In [13]:
import pandas as pd
import numpy as np
import os
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from tqdm import tqdm


In [14]:

# --- CONFIGURACIÓN ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🚀 Usando dispositivo: {device}")

csv_path = 'Datos/metadata.csv'
images_dir = 'Datos/images'

# ==========================================
# 1. PREPARACIÓN DE DATOS
# ==========================================
print("\n⚙️ Procesando datos...")
df = pd.read_csv(csv_path)

# A) Limpieza Tabular y One-Hot
# Quitamos columnas que no son features (ID, paths, etc)
cols_ignore = ['patient_id', 'lesion_id', 'img_id', 'diagnostic', 'path', 'biopsed']
# Seleccionamos columnas tabulares
tab_df = df.drop(columns=[c for c in cols_ignore if c in df.columns], errors='ignore').copy()

# Rellenar Nulos
for col in tab_df.columns:
    if tab_df[col].dtype == 'object':
        tab_df[col] = tab_df[col].fillna('DESCONOCIDO')
    else:
        tab_df[col] = tab_df[col].fillna(tab_df[col].mean())

# One-Hot Encoding
tab_df = pd.get_dummies(tab_df, drop_first=True)

# IMPORTANTE: Escalar datos numéricos (Neural Networks aman el rango 0-1 o -1 a 1)
scaler = StandardScaler()
X_tab_scaled = scaler.fit_transform(tab_df)

# B) Preparar Target
le = LabelEncoder()
y_labels = le.fit_transform(df['diagnostic'])
num_classes = len(le.classes_)
num_tab_features = X_tab_scaled.shape[1]

print(f"   - Features Tabulares: {num_tab_features}")
print(f"   - Clases: {le.classes_}")

# C) Split Train/Val/Test
# Creamos índices para dividir
indices = np.arange(len(df))
idx_train_val, idx_test, y_train_val, y_test = train_test_split(indices, y_labels, test_size=0.2, stratify=y_labels, random_state=42)
idx_train, idx_val, y_train, y_val = train_test_split(idx_train_val, y_train_val, test_size=0.25, stratify=y_train_val, random_state=42)


🚀 Usando dispositivo: cpu

⚙️ Procesando datos...
   - Features Tabulares: 66
   - Clases: ['ACK' 'BCC' 'MEL' 'NEV' 'SCC' 'SEK']


In [15]:

# ==========================================
# 2. DATASET MIXTO PERSONALIZADO
# ==========================================
class MixedDataset(Dataset):
    def __init__(self, dataframe, tabular_data, labels, indices, root_dir, transform=None):
        self.df = dataframe.iloc[indices].reset_index(drop=True)
        self.tab_data = tabular_data[indices]
        self.labels = labels[indices]
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        # 1. Imagen
        row = self.df.iloc[idx]
        img_path = os.path.join(self.root_dir, row['diagnostic'], row['img_id'])
        try:
            image = Image.open(img_path).convert('RGB')
        except:
            image = Image.new('RGB', (224, 224))
        
        if self.transform:
            image = self.transform(image)
            
        # 2. Tabular (Convertir a float32 para PyTorch)
        tab_input = torch.tensor(self.tab_data[idx], dtype=torch.float32)
        
        # 3. Label (Convertir a long)
        label = torch.tensor(self.labels[idx], dtype=torch.long)
        
        return image, tab_input, label

# Transformación "Squish" (Sin recorte)
transforms_squish = transforms.Compose([
    transforms.Resize((224, 224)), # <--- La clave para no recortar
    transforms.RandomHorizontalFlip(), # Data augmentation suave
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

val_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# DataLoaders
train_ds = MixedDataset(df, X_tab_scaled, y_labels, idx_train, images_dir, transforms_squish)
val_ds = MixedDataset(df, X_tab_scaled, y_labels, idx_val, images_dir, val_transforms)
test_ds = MixedDataset(df, X_tab_scaled, y_labels, idx_test, images_dir, val_transforms)

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=32, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=32, shuffle=False)

# ==========================================
# 3. ARQUITECTURA DE LA RED NEURONAL MIXTA
# ==========================================
class MixedNetwork(nn.Module):
    def __init__(self, num_tab_cols, num_classes):
        super(MixedNetwork, self).__init__()
        
        # RAMA 1: IMAGEN (ResNet18)
        # Usamos ResNet18 porque es más ligera que la 101 y entrena más rápido end-to-end
        self.cnn = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        num_cnn_features = self.cnn.fc.in_features # Suele ser 512
        # Quitamos la capa clasificadora original
        self.cnn.fc = nn.Identity()
        
        # RAMA 2: TABULAR (MLP pequeño)
        self.tab_branch = nn.Sequential(
            nn.Linear(num_tab_cols, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU()
        )
        
        # FUSIÓN (CONCATENACIÓN)
        # 512 (Imagen) + 64 (Tabular) = 576
        combined_features = num_cnn_features + 64
        
        # CABEZA CLASIFICADORA FINAL
        self.classifier = nn.Sequential(
            nn.Linear(combined_features, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(256, num_classes) # Salida final
        )

    def forward(self, image, tab_data):
        # Procesar imagen
        x_img = self.cnn(image) # (Batch, 512)
        
        # Procesar tabular
        x_tab = self.tab_branch(tab_data) # (Batch, 64)
        
        # Concatenar
        x_combined = torch.cat((x_img, x_tab), dim=1) # (Batch, 576)
        
        # Clasificar
        output = self.classifier(x_combined)
        return output


In [16]:
print("\n🧠 Inicializando Modelo End-to-End...")
model = MixedNetwork(num_tab_features, num_classes).to(device)

# Optimizador y Loss
# LR bajo (1e-4) porque estamos haciendo finetuning de toda la red y no queremos romper los pesos de ResNet
optimizer = optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

# ==========================================
# 4. BUCLE DE ENTRENAMIENTO (TRAINING LOOP)
# ==========================================
epochs = 10 # Ajusta según paciencia

print(f"\n🔥 INICIANDO FINETUNING BESTIA ({epochs} Épocas)...")
for epoch in range(epochs):
    # --- TRAIN ---
    model.train()
    train_loss = 0.0
    correct_train = 0
    total_train = 0
    
    loop = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} [Train]")
    for images, tabs, labels in loop:
        images, tabs, labels = images.to(device), tabs.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = model(images, tabs) # Forward Pass
        loss = criterion(outputs, labels)
        
        loss.backward() # Backward Pass (Calcula gradientes para Imagen Y Tabular)
        optimizer.step()
        
        train_loss += loss.item() * images.size(0)
        _, predicted = torch.max(outputs, 1)
        total_train += labels.size(0)
        correct_train += (predicted == labels).sum().item()
        
        # Actualizar barra de progreso
        loop.set_postfix(loss=loss.item())

    epoch_loss_train = train_loss / total_train
    epoch_acc_train = correct_train / total_train

    # --- VALIDATION ---
    model.eval()
    val_loss = 0.0
    correct_val = 0
    total_val = 0
    
    with torch.no_grad():
        for images, tabs, labels in val_loader:
            images, tabs, labels = images.to(device), tabs.to(device), labels.to(device)
            outputs = model(images, tabs)
            loss = criterion(outputs, labels)
            
            val_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            total_val += labels.size(0)
            correct_val += (predicted == labels).sum().item()
            
    epoch_loss_val = val_loss / total_val
    epoch_acc_val = correct_val / total_val

    # --- PRINT STATS ---
    print(f"   Train Loss: {epoch_loss_train:.4f} | Train Acc: {epoch_acc_train:.2%}")
    print(f"   Val Loss:   {epoch_loss_val:.4f} | Val Acc:   {epoch_acc_val:.2%}")
    print("-" * 60)

# ==========================================
# 5. EVALUACIÓN FINAL (TEST)
# ==========================================
print("\n🏆 Evaluando en conjunto de TEST...")
model.eval()
y_true = []
y_pred = []

with torch.no_grad():
    for images, tabs, labels in tqdm(test_loader, desc="Testing"):
        images, tabs, labels = images.to(device), tabs.to(device), labels.to(device)
        outputs = model(images, tabs)
        _, predicted = torch.max(outputs, 1)
        
        y_true.extend(labels.cpu().numpy())
        y_pred.extend(predicted.cpu().numpy())

print("\n--- INFORME FINAL (Red Mixta End-to-End) ---")
print(f"Accuracy Global: {accuracy_score(y_true, y_pred):.4f}")
print(classification_report(y_true, y_pred, target_names=le.classes_))


🧠 Inicializando Modelo End-to-End...

🔥 INICIANDO FINETUNING BESTIA (10 Épocas)...


Epoch 1/10 [Train]: 100%|██████████| 15/15 [01:01<00:00,  4.08s/it, loss=1.59]


   Train Loss: 1.6974 | Train Acc: 30.83%
   Val Loss:   1.5779 | Val Acc:   36.65%
------------------------------------------------------------


Epoch 2/10 [Train]: 100%|██████████| 15/15 [00:59<00:00,  3.94s/it, loss=1.08]


   Train Loss: 1.1570 | Train Acc: 63.54%
   Val Loss:   1.3856 | Val Acc:   43.48%
------------------------------------------------------------


Epoch 3/10 [Train]: 100%|██████████| 15/15 [00:57<00:00,  3.86s/it, loss=0.749]


   Train Loss: 0.8721 | Train Acc: 77.50%
   Val Loss:   1.3006 | Val Acc:   49.07%
------------------------------------------------------------


Epoch 4/10 [Train]: 100%|██████████| 15/15 [00:59<00:00,  3.98s/it, loss=0.589]


   Train Loss: 0.6566 | Train Acc: 85.83%
   Val Loss:   1.2904 | Val Acc:   47.20%
------------------------------------------------------------


Epoch 5/10 [Train]: 100%|██████████| 15/15 [00:57<00:00,  3.84s/it, loss=0.481]


   Train Loss: 0.4888 | Train Acc: 92.92%
   Val Loss:   1.2479 | Val Acc:   47.20%
------------------------------------------------------------


Epoch 6/10 [Train]: 100%|██████████| 15/15 [00:58<00:00,  3.87s/it, loss=0.454]


   Train Loss: 0.3625 | Train Acc: 95.42%
   Val Loss:   1.2605 | Val Acc:   50.93%
------------------------------------------------------------


Epoch 7/10 [Train]: 100%|██████████| 15/15 [00:58<00:00,  3.91s/it, loss=0.201]


   Train Loss: 0.2730 | Train Acc: 98.12%
   Val Loss:   1.2698 | Val Acc:   49.69%
------------------------------------------------------------


Epoch 8/10 [Train]: 100%|██████████| 15/15 [00:59<00:00,  3.97s/it, loss=0.19] 


   Train Loss: 0.2022 | Train Acc: 98.75%
   Val Loss:   1.2671 | Val Acc:   49.69%
------------------------------------------------------------


Epoch 9/10 [Train]: 100%|██████████| 15/15 [00:57<00:00,  3.82s/it, loss=0.181]


   Train Loss: 0.1489 | Train Acc: 99.58%
   Val Loss:   1.2678 | Val Acc:   50.31%
------------------------------------------------------------


Epoch 10/10 [Train]: 100%|██████████| 15/15 [00:59<00:00,  3.99s/it, loss=0.0936]


   Train Loss: 0.1150 | Train Acc: 99.58%
   Val Loss:   1.2608 | Val Acc:   52.17%
------------------------------------------------------------

🏆 Evaluando en conjunto de TEST...


Testing: 100%|██████████| 6/6 [00:10<00:00,  1.82s/it]


--- INFORME FINAL (Red Mixta End-to-End) ---
Accuracy Global: 0.5093
              precision    recall  f1-score   support

         ACK       0.52      0.47      0.49        30
         BCC       0.37      0.43      0.40        30
         MEL       0.50      0.36      0.42        11
         NEV       0.54      0.70      0.61        30
         SCC       0.45      0.33      0.38        30
         SEK       0.67      0.67      0.67        30

    accuracy                           0.51       161
   macro avg       0.51      0.49      0.50       161
weighted avg       0.51      0.51      0.50       161

